stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - dataset
  preprocess:
    cmd: python src/text_preprocessing.py
    deps:
    - src/text_preprocessing.py
  train:
    cmd: python src/text_classification.py AdaBoost
    deps:
    - src/text_classification.py
